fix(python): modify validation of attribute data
linkernetworks/visionai-data-format pull request #27
Opened 2023-05-09 07:28 UTC by christianmasa

## Purpose

add missing `confidence_score` field for dynamic context data and fix wrong type mapping.

## What Changes?
- add `confidence_score` field for dynamic objects
- remove unused attribute naming replacement, since we let user to build the project data with our ontology. ( `option` in dataverse equals with `vec` attribute. we don't need to replace it since anymore since we have our own ontology)

## What to Check?

it should work. Dataverse could import dataset normally.

2023-05-09 09:54 UTC, christianmasa commented on visionai_data_format/schemas/utils/validators.py
> -
wrong type mapping

2023-05-10 05:29 UTC, JasperSui approved these changes

2023-05-10 05:30 UTC, JasperSui requested changes

2023-05-10 05:30 UTC, JasperSui commented on visionai_data_format/schemas/common.py
> +        return data
Should we override the `json` as well?

2023-05-10 05:35 UTC, linkeralbertlo approved these changes

2023-05-10 05:55 UTC, christianmasa commented on visionai_data_format/schemas/common.py
> +        return data
yes, looks like we should override some existing functions of `BaseModel` to exclude none value.

2023-05-10 09:53 UTC, christianmasa commented on visionai_data_format/schemas/common.py
> +        return data
done

2023-05-11 02:42 UTC, JasperSui approved these changes

2023-05-11 05:20 UTC, linkeralbertlo approved these changes

2023-05-11 05:57 UTC, yihsuan123 approved these changes

2023-05-11 07:28 UTC, christianmasa commented on visionai_data_format/schemas/utils/validators.py
> +        return f"Attribute {root_key} with classes {extra_classes} doesn't accepted"
add `root_key` information to know which part led to error

2023-05-11 09:44 UTC, JasperSui approved these changes
Does this PR fix the `'dontcare'` and `'*tagging'` parts as well?

2023-05-11 09:46 UTC, linkeralbertlo approved these changes

2023-05-11 10:04 UTC, yihsuan123 approved these changes

2023-05-11 10:30 UTC, christianmasa commented
> Does this PR fix the `'dontcare'` and `'*tagging'` parts as well?

the *tagging and `dontcare` were the mistake made by our data. 

*tagging problem was when we create the visionai ontology missing the information

`dontcare` problem was raised because we put our data in frame `contexts` instead of `objects`

2023-05-12 04:09 UTC, merged